Add aminoacid position and update readme
aki2274/KOnezumi-AID pull request #105
Opened 2024-07-10 05:57 UTC by aki2274

- 2か所のエラーの修正を行いました．
- 1転写産物で検索される場合にアミノ酸が何番目であるかの表示をするようにしました．
- [複数転写産物がある場合のロジックが間違えていたので修正しました．](https://github.com/aki2274/KOnezumi-AID/commit/cbaf9e71452ae02978e821f36a6e19d6ecda3582)
- [ 遺伝子シンボルの入力であっても，1つの転写産物しか持たない場合に転写産物検索と同じ情報を含めるようにしました．](https://github.com/aki2274/KOnezumi-AID/commit/eb2b2518fa1875b41c07ccc772ca47201fefdfdd)
- ptcとスプライスサイトのロジックを分けました
- readmeのアップデートをおこないました

1つのPRにまとめてしまい申し訳ありません．以上の5点について修正しました．

2024-07-10 12:10 UTC, aki2274 commented
#87 #101

2024-07-10 23:33 UTC, akikuno requested changes

2024-07-10 23:33 UTC, akikuno commented on src/konezumiaid/main.py
> +            recomend = [not d["in_start_150bp"] for d in list_of_dict]
- typo: recomend -> recommend
- type hintingで型はすでに明示されているので、`list_of_dict`は具体的な変数名としたほうが良いでしょう

2024-07-10 23:33 UTC, akikuno commented on src/konezumiaid/main.py
> +def extract_matching_seqs(lists, flag_ptc=False) -> list[dict]:
`lists`も具体的な名称が好ましいです

2024-07-11 03:28 UTC, aki2274 commented
型ヒントの抜けや変数名の修正を行いました．読みにくくて申し訳ありません．

2024-07-11 03:57 UTC, akikuno commented on src/konezumiaid/main.py
> +def extract_matching_seqs(candidate_gene_primers: list[list], flag_ptc: bool = False) -> list[dict]:
`d in lists[0] if d["seq"] in common_seqs`が4回も出てくるので、一箇所にまとめても良いかもしれません。

```python

def extract_matching_seqs(lists, flag_ptc=False) -> list[dict]:
    seq_sets = [set(d["seq"] for d in lst) for lst in lists]
    common_seqs = set.intersection(*seq_sets)

    common_data = [
        (d["seq"], d["link_to_crisprdirect"], d.get("aminoacid"))
        for d in lists[0] if d["seq"] in common_seqs
    ]

    if flag_ptc:
        target_aminoacids = [aa[-1:] if aa else None for _, _, aa in common_data]
    else:
        target_aminoacids = [None for _ in common_data]

    result = [
        {"Target sequence (20mer + PAM)": seq, "Target amino acid": aa, "link to CRISPRdirect": link}
        for (seq, link, _), aa in zip(common_data, target_aminoacids)
    ]
    
    return pd.DataFrame(result)

```

2024-07-11 04:23 UTC, aki2274 commented on src/konezumiaid/main.py
> +def extract_matching_seqs(candidate_gene_primers: list[list], flag_ptc: bool = False) -> list[dict]:
こちら少し違う形で修正しました．
また，スプライスサイトを狙うgRNAについてエクソン番号は一意に定まらないので削除しました．

2024-07-12 00:31 UTC, akikuno approved these changes
LGTMです！

2024-07-12 00:31 UTC, akikuno commented on src/konezumiaid/main.py
> +    if not df_ptc_gRNA.empty:
細かいところなので記憶に留めるだけで結構ですが、`if not xxx.empty`よりも`if xxx.exist`のほうが認識しやすいため、代替が可能であるならば`exist`のほうがbetterです☺

2024-07-12 05:33 UTC, aki2274 commented on src/konezumiaid/main.py
> +    if not df_ptc_gRNA.empty:
承知しました．notが可読性を下げているという認識でよろしいでしょうか．また，DataFrame型でexistにあたるメソッドが見つからなかったのですがありますか？

2024-07-12 05:35 UTC, merged